apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: aircraft-postgres-cluster
spec:
  instances: 1

  bootstrap:
    initdb:
      database: historian
      owner: historian
      secret:
        name: postgres-historian-password-secret

  storage:
    size: 1Gi
